version: '3'
services:

  # NestJS App Service
  nestjs-app:
    image: node:18
    volumes:
      - ./:/usr/src/app
      - ./env.dev:/usr/src/app/env.dev
    depends_on:
      - mongodb
    working_dir: /usr/src/app
    logging:
      driver: "json-file"
      options: { "max-size": "1m", "max-file": "1" }
    expose:
      - 4000
    ports:
      - 4000:4000
    command: npm run start:dev

  # MongoDB Service
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"  # Map MongoDB container port to host port
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
